#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Usage: phone searchfor[...searchfor]"
	echo "(you didn't tell me what you want to search for.)"
else
	str=""
	
	for arg in $*
	do
		if [ "$str" = "" ]
		then 
			str="$arg"
		else
			str="$str|$arg"
		fi
		
	done
	

	egrep -i "$str" mydata > result
	awk -f display.awk result
fi
	
